/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentation;

/**
 *
 * @author User
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home2
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        list = new javax.swing.JButton();
        tables = new javax.swing.JButton();
        attributes = new javax.swing.JButton();
        heading = new javax.swing.JButton();
        introduction = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        formating = new javax.swing.JButton();
        style = new javax.swing.JButton();
        paragraph = new javax.swing.JButton();
        tittle = new javax.swing.JButton();
        comment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HTML LEARNER");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        list.setBackground(new java.awt.Color(255, 51, 153));
        list.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        list.setText("Lists");
        list.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listActionPerformed(evt);
            }
        });

        tables.setBackground(new java.awt.Color(51, 204, 0));
        tables.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        tables.setText("Tables");
        tables.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablesActionPerformed(evt);
            }
        });

        attributes.setBackground(new java.awt.Color(204, 153, 0));
        attributes.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        attributes.setText("Attributes");
        attributes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        attributes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attributesActionPerformed(evt);
            }
        });

        heading.setBackground(new java.awt.Color(0, 102, 204));
        heading.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        heading.setText("Heading ");
        heading.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        heading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headingActionPerformed(evt);
            }
        });

        introduction.setBackground(new java.awt.Color(255, 102, 102));
        introduction.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        introduction.setText("Introduction");
        introduction.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        introduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introductionActionPerformed(evt);
            }
        });

        jButton1.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBox.icon.pressedBorderColor"));
        jButton1.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        formating.setBackground(new java.awt.Color(0, 255, 153));
        formating.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        formating.setText("Formating Tag");
        formating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatingActionPerformed(evt);
            }
        });

        style.setBackground(new java.awt.Color(0, 153, 153));
        style.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        style.setText("Style Tag");
        style.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                styleActionPerformed(evt);
            }
        });

        paragraph.setBackground(new java.awt.Color(255, 204, 204));
        paragraph.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        paragraph.setText("Paragraph");
        paragraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paragraphActionPerformed(evt);
            }
        });

        tittle.setBackground(new java.awt.Color(204, 204, 255));
        tittle.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tittle.setText("Title");
        tittle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tittleActionPerformed(evt);
            }
        });

        comment.setBackground(new java.awt.Color(102, 153, 255));
        comment.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        comment.setText("Comment");
        comment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(introduction, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formating)
                    .addComponent(comment, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(attributes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paragraph, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(style, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tables, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heading, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(introduction)
                    .addComponent(paragraph)
                    .addComponent(heading))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(list)
                    .addComponent(attributes)
                    .addComponent(tables))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formating)
                    .addComponent(style)
                    .addComponent(tittle))
                .addGap(60, 60, 60)
                .addComponent(comment)
                .addGap(109, 109, 109)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listActionPerformed
        lists l = new lists();
        l.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_listActionPerformed

    private void tablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablesActionPerformed
        table t = new table();
        t.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_tablesActionPerformed

    private void attributesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attributesActionPerformed
        attributes a = new  attributes();
        a.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_attributesActionPerformed

    private void headingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headingActionPerformed
          heading hd = new heading();
          hd.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_headingActionPerformed

    private void introductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introductionActionPerformed
        introduction intro = new introduction();
        intro.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_introductionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        start s = new start();
        s.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatingActionPerformed
        // TODO add your handling code here:
        formating_tag ft = new formating_tag();
        ft.setVisible(true);
        dispose();
    }//GEN-LAST:event_formatingActionPerformed

    private void styleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_styleActionPerformed
        // TODO add your handling code here:
          style st = new style();
         st.setVisible(true);
        dispose();
    }//GEN-LAST:event_styleActionPerformed

    private void paragraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paragraphActionPerformed
        // TODO add your handling code here:
          paragraph pg = new paragraph();
          pg.setVisible(true);
        dispose();
    }//GEN-LAST:event_paragraphActionPerformed

    private void tittleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tittleActionPerformed
        // TODO add your handling code here:
          tittle ttl = new tittle();
          ttl.setVisible(true);
        dispose();
    }//GEN-LAST:event_tittleActionPerformed

    private void commentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentActionPerformed
        // TODO add your handling code here:
        comment cmt = new comment();
        cmt.setVisible(true);
        dispose();
    }//GEN-LAST:event_commentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attributes;
    private javax.swing.JButton comment;
    private javax.swing.JButton formating;
    private javax.swing.JButton heading;
    private javax.swing.JButton introduction;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton list;
    private javax.swing.JButton paragraph;
    private javax.swing.JButton style;
    private javax.swing.JButton tables;
    private javax.swing.JButton tittle;
    // End of variables declaration//GEN-END:variables
}
